# Cut a release whenever a new tag is pushed to the repo.
name: Release

on:
  # Or, developers can manually push a tag from their clone
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Build release artifacts and prepare release notes
        run: |
          .github/workflows/release_prep.sh ${{ github.ref_name }} > release_notes.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          # Use GH feature to populate the changelog automatically
          generate_release_notes: true
          body_path: release_notes.txt
          fail_on_unmatched_files: true
          files: cmake_configure_file-*.tar.gz
          tag_name: ${{ github.ref_name }}
